### PR TITLE
Support multiple versions of DC/OS

### PR DESCRIPTION
**Pull request by wolf31o2**
NOTE: This is a breaking change!

Introduce support for multiple versions of DC/OS. This is currently
supported from DC/OS 1.8.7 through 1.9.3 and EarlyAccess.

- Improve IP detection
  - Simplify AWS/GCE selection
  - Always detect address from host, versus static via Ohai
- Dependency / prerequisite updates
  - Bumped selinux cookbook for newer Chef compatibility
  - Stop and disable rsyslog service
  - Ensure curl, tar, and xz are present
  - Disable IPv6 with sysctl cookbook
  - Allow disabling management of Docker for advanced setups
- Update Tests
  - Increase resources for Vagrant-based tests
  - Use CentOS 7.3
  - Use loopback for IP detection
- Miscellaneous updates
  - Move downloads to /usr/src/dcos
  - Support arbitrary configuration values, verus static list
  - Avoid notifies/subscribes for idempotency
  - Use multi package for installs
  - Increase minimum required Chef version to 12.1

Signed-off-by: Chris Gianelloni <wolf31o2@gmail.com>

### CODE REVIEW

**Comment by wolf31o2** [comment]
I have readme and more testing updates coming. If you'd rather wait for those, I understand.

**Comment by jjasghar** [comment]
Nope, more the better. I dedicate some time to verifying this as soon as you're ready for this to be tested.

**Comment by wolf31o2** [comment]
I updated the README and rebased. The additional tests I mentioned are InSpec tests, which I will do in another pull request. This is ready for review.

**Comment by ghost** [comment]
@jjasghar let me know if there's anything I can do to help with this.

**Comment by ghost** [comment]
I added DC/OS 1.9.5 and 1.10.1 support. Let me know before merging this, so I can rebase/squash it.

**Comment by ghost** [comment]
Also, there's integration tests. They passed.

**Comment by jjasghar** [comment]
I'll release this today.

**Pull request merged**
